# Built with Jekyll 3.2.0

# Setup
title:               KK的自留地
tagline:             'Expect the unexpected,and whenever possible,be the unexpected'
description:         '互联网产品经理，主要负责广告系统以及2B类产品。读书偏向于历史、思维、投资方面，吉他入门水平，Crossfit爱好者'
url:                 'http://daoism-kk.github.io'
baseurl:             ''

# About/contact
author:
  name:              kai kang
  url:               https://twitter.com/
  email:             kstzyy@gmail.com

paginate:            5

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


#podcast seetings
podcast_url: http://www.daoism.me/podcast
podcast_album_art: /assets/podcast_picture.jpg
podcast_title: 文化中国月旦谈
podcast_owner: kai kang
podcast_email: kstzyy@gmail.com
podcast_category: Society & Culture
podcast_subcategory_one: Philosophy
podcast_subcategory_two: Personal Journals
podcast_explicit: "no"
podcast_author: kai kang
podcast_description:  探讨接地气的话题，让文化中国人的观点和看法得到沉淀。
podcast_summary: 通过职业/生活/读书等多方面的话题，在实际中促进文化中国人的思考和交流
podcast_subtitle: hosted by kaikang,hope you like it
site_url: http://www.daoism.me



